"""Add grade column

Revision ID: 1e9dc9156ded
Revises: 1001fbb1793a
Create Date: 2023-08-10 15:19:31.868374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e9dc9156ded'
down_revision = '1001fbb1793a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('parent_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('parent_name')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
