"""Migration Number 002

Revision ID: 62aaf300468f
Revises: d2c826b902c1
Create Date: 2023-08-18 14:12:26.216535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62aaf300468f'
down_revision = 'd2c826b902c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Class_Teacher', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=100), nullable=True))
        batch_op.drop_index('user_name')
        batch_op.create_unique_constraint(None, ['Class_Teacher'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('user_name', ['user_name'], unique=False)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('Class_Teacher')

    # ### end Alembic commands ###
